### ISSUE TITLE
Show where we got the URL from

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#18]
In the console output.
- .pulldown.json
- a custom resolver on the pulldown api server
- cdn js
- failed

**Comment by tgvashworth** [comment]
IMPOSSIBRU

**Comment by tgvashworth** [comment]
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm1V6iLNVjcMS3wtLSew5y8wcmT5RrqTW10yoVS9cNi5qkhOvc)

**Comment by jackfranklin** [comment]
![](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSWWNRS0IrubEqQIh1VVbtcO5AWVx9hv3fUkb2eatfTtDDfsqmMLw)
