### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#23]
I'm a bit clueless here as to how to test this thing, but it definitely needs some.

I guess we should test that certain searches produce the network requests we expect?

Thoughts welcome.

**Comment by tgvashworth** [comment]
The constructor is exported, so you can swap out/mock things on the prototype, like getFiles. Fake some API responses and see how it resolves things.

The argument passing can be mocked too, so we can check for the right output for given arguments.

**Comment by jackfranklin** [comment]
Ahh good point.

I'd argue that the most important bit of the CLI tool is parsing the arguments, so we can override `getFiles` and see what's passed into it, and assert it's what we expect, that kind of thing.

**Comment by jackfranklin** [comment]
Once the double comments pull req is merged, we will have some tests and I then plan to add more. Once that's done I'll set up Travis CI too :)

**Comment by tgvashworth** [comment]
Tests are now a thing.
