### ISSUE TITLE
CLI for creating custom things?

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#32]
```
$ pulldown new foo:http://foo.com/foo.js
$ pulldown foo
-> foo downloaded
```

Thinking something like that? Not sure I like the API like that though. Perhaps it should be:

```
$ pulldown --new foo:http://foo.com/foo.js
```

We can then save that to the pulldown.json file?

**Comment by jackfranklin** [comment]
As @phuu just pointed out to me, we'd also need the ability to add sets.

```
$ pulldown --new customset http://... http://... http://...
```

Maybe. I wonder how many people actually use the custom stuff though.

**Comment by latentflip** [comment]
Could do it the npm sorta way:

`pulldown http://foo.com/foo.js --save`

I guess that doesn't let you rename it

`pulldown http://foo.com/foo.js --save foo`

**Comment by tgvashworth** [comment]
Not sure I like the `--new` syntax. The git CLI would suggest something like  `pulldown set create backbone -- http://... http://... http://...` which I think is a little verbose.

Crazy idea: new CLI thing (not called pulldown) that's interoperable that lets you build sets.

**Comment by tgvashworth** [comment]
Ok that was a silly idea.

Jack, what's the reason you thought of this? Some specific thing you wanted to do but couldn't, presumably.

**Comment by jackfranklin** [comment]
Closing this. It totes isn't needed.
