### ISSUE TITLE
List sets

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#38]
I'd like to enhance the sets we have in the API. Once that's done, it would be good to add a command to list them:

```
$ pulldown --list-sets
-> Backbone [backbone.js, jquery.js, underscore.js]
-> Ember [ember.js, jquery.js, handlebars.js]
-> and so on
```

(API up for discussion)

**Comment by tgvashworth** [comment]
Yep, totes up for this. You could actually just hit `/` and list all the arrays:

``` json

{
  "html5shiv": "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js",
  "underscore": "underscore.js",
  "backbone": [
    "backbone.js",
    "underscore",
    "jquery"
  ],
  "marionette": [
    "backbone",
    "backbone.marionette"
  ],
  "bootstrap": "http://twitter.github.io/bootstrap/assets/bootstrap.zip"
}
```

**Comment by tgvashworth** [comment]
Also `pulldown ls`?

**Comment by jackfranklin** [comment]
> You could actually just hit / and list all the arrays

Yeah that works.

> Also `pulldown ls`

Yeah.

Will open another issue in the API repo to discuss sets.
