### ISSUE TITLE
Dry run

### ISSUE THREAD

**Issue by tgvashworth** [jackfranklin/pulldown#40]
I would like to be able to do a pulldown 'dry-run' where I try see what _would_ happen, but not actually do it.

```
pulldown -d/--dry-run jquery
```

This would also enable a kind of search mode: "hey pulldown, do you have this?". Currently I search cdnjs before using pulldown for a new thing.

**Comment by jackfranklin** [comment]
+1 would use.

> Currently I search cdnjs before using pulldown for a new thing.

Interesting. I never do, I just run pulldown and hope :dancers:

**Comment by tgvashworth** [comment]
It's also useful to check that you've got the right files going to the right places – because there's some weird shit going on, bug to follow.

**Comment by jackfranklin** [comment]
Cool. This should be as simple as changing the method that downloads a file just to do the output but not the actual downloading.
