### ISSUE TITLE
Target files with slashes break stuff

### ISSUE THREAD

**Issue by tgvashworth** [jackfranklin/pulldown#42]
```
~/dev/tmp/bomb
❯ pulldown jquery::fish/jq.js

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, open 'fish/jq.js'
```

**Comment by jackfranklin** [comment]
So we need to parse out `fish/jq.js`, check the directories exist and then write the file.

**Comment by tgvashworth** [comment]
Yarp. Question is – is that relative to -o, or the cwd?

**Comment by jackfranklin** [comment]
Definitely relative to the directory pulldown was run from.

**Comment by jackfranklin** [comment]
We seem to inadvertently have made 2 ways to do the same thing here.

IMO, these should do the same thing:

```
$ pulldown jquery::bah.js -o foo
$ pulldown jquery::foo/bah.js
```

Do we want to do that?

**Comment by tgvashworth** [comment]
That's true – I think yes.

_But_, this is fine:

```
pulldown jquery::bar.js -o foo -> ./foo/bar.js
pulldown jquery::foo/bar.js -> ./foo/bar.js
```

But does this make sense?

```
pulldown jquery::foo/bar.js -o baz -> ./foo/bar.js
```

Should it be this?

```
pulldown jquery::foo/bar.js -o baz -> ./baz/foo/bar.js
```

I know that's what you were saying (that it shouldn't), but it's definitely weird. It's basically a question of which takes priority, I guess?

**Comment by jackfranklin** [comment]
That's weird.

Tempted to say if we detect folder path in `jquery::foo/baa.js` bit, and `-o` is passed, we error.

So these are all fine:

```
$ pulldown jquery::foo.js -o bar => bar/foo.js
$ pulldown jquery::bar/foo.js => bar/foo.js
```

But this is just not cool, and IMO should not allow it and output a warning

```
$ pulldown jquery::bar/foo.js -o baz
-> Warning: instructions are ambiguous. 
```

**Comment by jackfranklin** [comment]
@phuu I may start work on this tonight. Are you happy with the above?
