### ISSUE TITLE
Prompt for update

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#46]
I don't know if this is possible.

But it would be great if we had some version checker in place so Pulldown could tell the user they should reinstall it.

```
$ pulldown foo
-> you're using Pulldown 0.4.0, which is outdated. (Latest is 0.5.0).
-> foo was downloaded to foo.com..
```

(Maybe an API endpoint?)

**Comment by tgvashworth** [comment]
[update-notifier](https://github.com/yeoman/update-notifier) from yeoman, maybe?

**Comment by jackfranklin** [comment]
Aww hell yeah!
