### ISSUE TITLE
Pulldown vs Bower

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#60]
People keep asking me which to use. In my mind, Pulldown's use case is completely different from Bowers - and Pulldown's not designed to compete. I should write this up.

**Comment by jackfranklin** [comment]
@phuu et all pls read and see if this makes sense.

### Isn't it like Bower?

Bower is a far more complex and fully-featured package and, more importantly, _dependency_ manager. If you have a complex project with multiple 3rd party libraries in play, and you want to keep tight control over the versions you're using, Bower is best suited. Use Bower when you wouldn't want to commit all those libraries to Git, but would want to commit a component.json file.

We envisage (and personally use) Pulldown for those times when you just want one or two libraries, and have little care for versioning or dependencies. For example, if I want to prototype a quick Backbone app, I can quickly run `$ pulldown jquery underscore backbone.js` (or `$ pulldown backbone`, which gets all 3). Here it doesn't matter to me which versions I have (Pulldown will always pull in the latest stable version by default) and I'll probably commit those libraries to Git too.

---

**Comment by latentflip** [comment]
+1 although it's not clear why at first you say it's not a dependency manager, but then say you can do `pulldown backbone` which pulls in all 3, implying it might be a kind of dependency manager

**Comment by jackfranklin** [comment]
@latentflip thanks - that's a fair point also. Should clarify Pulldown's concept of sets and how dumb it is.

**Comment by jackfranklin** [comment]
### Take 2

Bower is a far more complex and fully-featured package and, more importantly, dependency manager. If you have a complex project with multiple 3rd party libraries in play, and you want to keep tight control over the versions you're using, Bower is best suited. Use Bower when you wouldn't want to commit all those libraries to Git, but would want to commit a component.json file.

We envisage (and personally use) Pulldown for those times when you just want one or two libraries, and have little care for versioning or dependencies. For example, if I want to prototype a quick Backbone app, I can quickly run `$ pulldown jquery underscore backbone.js` to get all three. Here it doesn't matter to me which versions I have (Pulldown will always pull in the latest stable version by default) and I'll probably commit those libraries to Git too. Pulldown also has the concept of _sets_, which is often where people get confused. These two commands are equal:

```
$ pulldown jquery underscore backbone.js
$ pulldown backbone
```

The second command will download the Backbone _set_, which will give you Underscore, jQuery and Backbone. This looks like dependency management - and sort of is - but it's _really dumb_. All Pulldown is doing here is seeing you asked it for "backbone", and replacing that with "jquery underscore backbone.js", which it then goes and gets separately. There's no version management or anything of the sort, the feature exists just to save you some typing.

**Comment by latentflip** [comment]
You probably want to briefly mention how pulldown _knows_ that backbone ===
underscore + jquery + backbone (it's just config not magic).

On 22 August 2013 23:09, Jack Franklin notifications@github.com wrote:

> Take 2
> 
> Bower is a far more complex and fully-featured package and, more
> importantly, dependency manager. If you have a complex project with
> multiple 3rd party libraries in play, and you want to keep tight control
> over the versions you're using, Bower is best suited. Use Bower when you
> wouldn't want to commit all those libraries to Git, but would want to
> commit a component.json file.
> 
> We envisage (and personally use) Pulldown for those times when you just
> want one or two libraries, and have little care for versioning or
> dependencies. For example, if I want to prototype a quick Backbone app, I
> can quickly run $ pulldown jquery underscore backbone.js to get all
> three. Here it doesn't matter to me which versions I have (Pulldown will
> always pull in the latest stable version by default) and I'll probably
> commit those libraries to Git too. Pulldown also has the concept of _sets_,
> which is often where people get confused. These two commands are equal:
> 
> $ pulldown jquery underscore backbone.js
> $ pulldown backbone
> 
> The second command will download the Backbone _set_, which will give you
> Underscore, jQuery and Backbone. This looks like dependency management -
> and sort of is - but it's _really dumb_. All Pulldown is doing here is
> seeing you asked it for "backbone", and replacing that with "jquery
> underscore backbone.js", which it then goes and gets separately. There's no
> version management or anything of the sort, the feature exists just to save
> you some typing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jackfranklin/pulldown/issues/60#issuecomment-23130145
> .

## 

Philip Roberts
latentflip.com

**Comment by leggetter** [comment]
:+1: to @latentflip's comment about how sets are defined and used.

**Comment by jackfranklin** [comment]
Agreed. 

### Take 3

Bower is a far more complex and fully-featured package and, more importantly, dependency manager. If you have a complex project with multiple 3rd party libraries in play, and you want to keep tight control over the versions you're using, Bower is best suited. Use Bower when you wouldn't want to commit all those libraries to Git, but would want to commit a component.json file.

We envisage (and personally use) Pulldown for those times when you just want one or two libraries, and have little care for versioning or dependencies. For example, if I want to prototype a quick Backbone app, I can quickly run `$ pulldown jquery underscore backbone.js` to get all three. Here it doesn't matter to me which versions I have (Pulldown will always pull in the latest stable version by default) and I'll probably commit those libraries to Git too. Pulldown also has the concept of _sets_, which is often where people get confused. These two commands are equal:

```
$ pulldown jquery underscore backbone.js
$ pulldown backbone
```

The second command will download the Backbone _set_, which will give you Underscore, jQuery and Backbone. This looks like dependency management - and sort of is - but it's _really dumb_. All Pulldown is doing here is seeing you asked it for "backbone", and replacing that with "jquery underscore backbone.js", which it then goes and gets separately. There's no version management or anything of the sort, the feature exists just to save you some typing. Pulldown doesn't magically detect these sets, either. These are all hard coded in the [Pulldown API](https://github.com/phuu/pulldown-api/blob/master/pulldown.json#L4).

**Comment by latentflip** [comment]
That reads pretty well to me :)

**Comment by leggetter** [comment]
The link could be substituted for a code example the same way the commands are shown - or in doc example snippet, then link. Just means all details are in a single place. But if this is likely to change then the link may be best.

**Comment by tgvashworth** [comment]
I think it's important to emphasise that pulldown is about getting a file, quickly – but only once. Perhaps:

> Bower is a package manager; Pulldown downloads files. Bower configurations can be saved with a project and shared by people working on it; Pulldown cannot – it is almost configuration-less. Think of it as way to get a copy of your favourite library, fast.

**Comment by jackfranklin** [comment]
Yeah I like that. Nice. I'll put that and mine together and add it into the README :thumbsup: Thanks for your help all.
