### ISSUE TITLE
-c --concat option

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#67]
Should minify the arguments (most come minified from cdnjs anyway) into one file, keeping the order in which they are passed.

**Comment by tgvashworth** [comment]
:-1: because of the risk of overcomplicating. Pulldown grabs files – we can add other layers with other projects, but at its core I think Pulldown has to stay very, very simple.

**Comment by jackfranklin** [comment]
Yeah - I sort of agree. I wonder if we need a Pulldown plugin system...kinda like Grunt...

Again, over complicating things maybe...

**Comment by jackfranklin** [comment]
Going to close this. Would like to revisit maybe down the line, but certainly not soon.
