### ISSUE TITLE
Destination folder for unzipping

### ISSUE THREAD

**Issue by egidijusz** [jackfranklin/pulldown#7]
First of all I want to say - this is awesome library! Thank you for making it :)

It would be very nice if when dealing with zip files it would take into account "output" value. I mean now zips are just unzipped in project folder no matter where "output" in .pulldownrc points. Seems that script tries to download zip file to path defined in "output", not unzip it there.

Sorry for my bad english.

**Comment by jackfranklin** [comment]
This makes sense - will look into this.

**Comment by jackfranklin** [comment]
As you might have seen, we've just completely rewritten Pulldown from the ground up. Currently we now have no support for zips at all (apologies for this) but will be looking to add them back in. As such I'm going to close this and make a new ticket for adding zip support.

Jack.
