### ISSUE TITLE
Local ~/.pulldown.json

### ISSUE THREAD

**Issue by adrian-chang** [jackfranklin/pulldown#8]
It seems pretty reasonable that you'd want a local pulldown.json per project that you're working on otherwise it would get messy as everything is global.

The suggestion would be to scan for a local pulldown.json file in the current directory, then to scan the home_directory, then fetch the default one if there is nothing to be found.

**Comment by jackfranklin** [comment]
You can do this right now with `.pulldownrc`: https://github.com/jackfranklin/pulldown#project-dependencies-with-the-pulldownrc-file

Is that what you're after?

**Comment by adrian-chang** [comment]
This is fairly close but not quite.

What I really want to do is more like this.

pulldown jquery:lib/jquery.js

The location of jquery is examined through a local rc file instead of the home directory location. I'm not sure the project configuration can do that as it has to install everything in one location instead of targeting.

**Comment by jackfranklin** [comment]
Ahh I see, sorry I misunderstood. 

Out of interest, what's the use case here?

It should be quite simple to implement.

**Comment by adrian-chang** [comment]
Well it's more of the case that not everyone who may work on a project is going to well keep their home directories the same. This forces it so that if contextually two people are in the same project, they are ensured to get the same source when they pulldown.

**Comment by jackfranklin** [comment]
Ahh yes. Makes perfect sense. I will work on this.

I'm imagining it should search recursively up directories until it finds one.

**Comment by jackfranklin** [comment]
Hey @amchang. Our new pulldown, which has been completely rewritten, now works completely differently on this. If you take a look and let me know what you think, that would be great. If you have any probs, please open a new ticket :)
