### ISSUE TITLE
Pulldown Bootstrap

### ISSUE THREAD

**Issue by chid** [jackfranklin/pulldown#83]
On git bash, running pulldown bootstrap

```
$ pulldown bootstrap
.....
-> Success: http://twitter.github.io/bootstrap/assets/bootstrap.zip was download
ed to ./bootstrap.zip
```

This actually just saves the HTML page. When it should be downloading https://github.com/twbs/bootstrap/releases/download/v3.0.2/bootstrap-3.0.2-dist.zip

**Comment by jackfranklin** [comment]
Hey @chid, thanks for this report! Will look into it today sometime.

**Comment by jackfranklin** [comment]
@phuu so the Pulldown API gives us back this for Bootstrap: `http://twitter.github.io/bootstrap/assets/bootstrap.zip`, which is incorrect.

CDNJS does give us bootstrap (http://cdnjs.com/libraries/twitter-bootstrap/), so we should be able to work something out here.

**Comment by jackfranklin** [comment]
Hey @chid, sorry for such a long delay in this. We actually removed support for ZIPs in Pulldown, I think around the time we hit V1. It was getting a bit complicated and we decided to simplify down to just dealing with URLs.

**Comment by chid** [comment]
No worries, sounds good.

**Comment by xiaohanyu** [comment]
Same problems. 

Could I just `pulldown twitter-bootstrap`? I saw a `twitter-bootstrap` project in cdnjs.
