### ISSUE TITLE
Ditch optimist

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#85]
Optimist has been deprecated: https://github.com/substack/node-optimist#deprecation-notice

We should swap to using minimist (https://npmjs.org/package/minimist), which is what Optimist used under the hood anyway.

**Comment by tgvashworth** [comment]
I think [yargs](https://github.com/chevex/yargs) might be better – totally drop in replacement/improvement afaik.

**Comment by jackfranklin** [comment]
Ah even better :)
